version: "3"
services:
  server:
    container_name: bootleg-spatial-recall
    image: latest/bootleg-spatial-recall
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    links:
      - db
    entrypoint: ["npm", "run", "start"]
  db:
    container_name: mongo
    image: mongo
    volumes:
      - /srv/docker/mongodb:/var/lib/mongodb
    ports:
      - '27017:27017'