version: "3"
services:
  server:
    container_name: bootleg-spatial-recall
    image: latest/bootleg-spatial-recall
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    links:
      - db
  test-server:
    container_name: bootleg-spatial-recall-test
    image: latest/bootleg-spatial-recall
    restart: always
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
    - MONGO_DB=testing
    volumes:
      - .:/usr/src/app
    links:
      - db
  db:
    container_name: mongo
    image: mongo
    volumes:
      - /srv/docker/mongodb:/var/lib/mongodb
    ports:
      - '27017:27017'