version: "3"
services:
  test-server:
    container_name: bootleg-spatial-recall-test
    image: latest/bootleg-spatial-recall
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - MONGO_DB=bootleg-spatial-recall
      - TEST_MONGO_DB=testing
      - JWT_SECRET=notagoodkey
      - JWT_EXPIRES_IN=30d
      - JWT_COOKIE_EXPIRES_IN=30d
      - NODE_ENV=test
    links:
      - db
    entrypoint: ["npm", "run", "start"]
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'